### ISSUE TITLE
Undefined module "bcsmartspace-google"

### ISSUE THREAD

**Issue by dsfssdfd** [DerpFest-AOSP/packages_apps_DerpLauncher#5]
[ 98% 393/398] analyzing Android.bp files and generating ninja file at out/soong
FAILED: out/soong/build.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename
 "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top 
"$TOP"     --soong_out "out/soong"     --out "out"     -o out/soong/build.ninja 
--globListDir build --globFile out/soong/globs-build.ninja -t -l out/.module_pat
hs/Android.bp.list --available_env out/soong/soong.environment.available --used_
env out/soong/soong.environment.used.build Android.bp
error: packages/apps/DerpLauncher/Android.bp:147:1: "Launcher3ResLib" depends on
 undefined module "bcsmartspace-google"
22:20:59 soong bootstrap failed with: exit status 1

**Comment by NurKeinNeid** [comment]
Obviously you can't read. It's clearly stated in org's readme.

**Comment by dsfssdfd** [comment]
sry just saw it

**Comment by NurKeinNeid** [comment]
Wait for tomorrow. I will publish then.
